# Generated by Django 5.2.4 on 2025-07-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='a unique name for a feature flag like slung', max_length=200, unique=True, verbose_name='title')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'feature flag',
                'verbose_name_plural': 'feature flags',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('create', 'create'), ('toggle', 'toggle'), ('auto_disable', 'auto disable'), ('dependency_add', 'dependency add')], default='create', max_length=100, verbose_name='log type')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='creatd at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='featureflag.featureflag', verbose_name='flag')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencies', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('dependent_flag', models.ForeignKey(help_text='The feature flag whose state is dependent on this rule.', on_delete=django.db.models.deletion.CASCADE, related_name='dependency_rules_as_dependent', to='featureflag.featureflag')),
                ('source_flag', models.ForeignKey(help_text='The feature flag that this rule evaluates against', on_delete=django.db.models.deletion.CASCADE, related_name='dependency_rules_as_source', to='featureflag.featureflag')),
            ],
            options={
                'verbose_name': 'dependency',
                'verbose_name_plural': 'dependencies',
                'unique_together': {('dependent_flag', 'source_flag')},
            },
        ),
    ]
